name: Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

permissions:
  contents: write

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - run: corepack enable && pnpm i

      - run: npm run build
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORKIT_GITHUB_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: boshen
          SPONSORKIT_GITHUB_TYPE: user

      - uses: EndBug/add-and-commit@v9
        with:
          add: "sponsors.*"
          message: "chore: update sponsors"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
